### ISSUE TITLE
Blade Runner

### ISSUE THREAD

**Issue by madmoose** [piranha/osgameclones#163]
I see you add my Blade Runner project at https://github.com/madmoose/replicant/

You might want to replace it with https://github.com/madmoose/scummvm/tree/bladerunner/engines/bladerunner which, while not super active, is a slightly less stalled reimplementation as a ScummVM engine.

**Comment by piranha** [comment]
@wonea any thoughts on this?

**Comment by wonea** [comment]
Look like Blade Runner may also be heading for ResidualVM as well.

Reverse Engineerin Blade Runner
http://westwoodbladerunner.blogspot.co.uk/

"Sunday, 8 February 2015
The Update
ResidualVM or ScummVM: I decided to go with ResidualVM since the actors and items will have a greater visual fidelity using a hardware based graphics layer. This past week I begain acquainting myself with the 0.2.1 code line. Being able to play Blade Runner from start to finish in ResidualVM is about a year, or more, away. "

I purpose adding another entry for Blade Runner to keep track of them all - put the SCUMMVM entry on top

**Comment by piranha** [comment]
So the ResidualVM project is in, cool.
