### ISSUE TITLE
Zatacka and Zatacka X are different projects

### ISSUE THREAD

**Issue by simenheg** [piranha/osgameclones#506]
Under "Zatacka" clones, Zatacka X is listed with the following homepage: http://zatacka.sourceforge.net/, but that is a different project. Zatacka X doesn't have a homepage apart from the GitHub repository page, https://github.com/simenheg/zatackax/.

**Comment by Tom4hawk** [comment]
I've change entry to Zatacka X - it's actively maintained.
Original Zatacka (http://zatacka.sourceforge.net/) has not been updated since 2007 and there is no repo available - we can either point to tar.gz file or ask @akien-mga to add sources to Libre Games Archive and point there.

Tell me which option is preferable and I'll add Zatacka after checking if it's even possible to compile it on new systems ;)
